# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_data'),
    ]

    operations = [
    ]
